version: "3.9"
services:
  one:
    image: unischeme:latest
    build:
      context: .
    ports: 
      - 5000:5000
    environment:
      - PORT=5000
      - NAME="one"
      - URL="one:5000"
    networks:
      - unischeme
  two:
    image: unischeme:latest
    build: 
      context: .
    ports: 
      - 5001:5000
    environment:
      - PORT=5000
      - NAME="two"
      - URL="two:5000"
    networks:
      - unischeme
networks:
  unischeme:
    
